# numbers = [4,5,2,1,"John",True]
# print(numbers[0])
# print(numbers[-1])

numbers = [4,5,2,1,2,5]
# print(numbers[0:3])
# print(numbers[1:])
# print(numbers[::2])
# numbers[0] = 25
# print(numbers)
# # for i in numbers:
# #     print(i)
# numbers.append(25)
# print(numbers)
# numbers.extend([25,27,30])
# print(numbers)
# print(numbers.count(2))
# print(numbers.index(5))
# numbers.insert(0,30)
# print(numbers)
# numbers.clear()
# print(numbers)
# numbers.remove(5)
# print(numbers)
# numbers.pop()
# print(numbers)
# numbers.pop(0)
# print(numbers)
# numbers.sort()
# print(numbers)
# numbers.sort(reverse=True)
# print(numbers)
# numbers.reverse()
# print(numbers)

print(len(numbers))
print(max(numbers))
print(min(numbers))
print(sum(numbers))
print(sorted(numbers))
print(sorted(numbers,reverse=True))